#!/bin/bash
COUNTRY="Mexico"
CURRENTDIR="$(cd "$(dirname "$0")"; pwd)"
LASTUPDATEFILE="${CURRENTDIR}/.worldometers-corona.log"
function sendData() {
	printf "$COUNTRY:\n\n" >> ${CURRENTDIR}/worldometers-data.tmp
	echo ""
        printf "Casos totales  : $1\n" >> ${CURRENTDIR}/worldometers-data.tmp
	printf "Casos nuevos   : $2\n" >> ${CURRENTDIR}/worldometers-data.tmp
	printf "Muertes totales: $3\n" >> ${CURRENTDIR}/worldometers-data.tmp
	printf "Muertes nuevas : $4\n" >> ${CURRENTDIR}/worldometers-data.tmp
	printf "Recuperados    : $5\n" >> ${CURRENTDIR}/worldometers-data.tmp
	printf "Casos activos  : $6\n" >> ${CURRENTDIR}/worldometers-data.tmp
        printf "Casos criticos : $7\n" >> ${CURRENTDIR}/worldometers-data.tmp
        printf "CT/Promedio    : $8\n" >> ${CURRENTDIR}/worldometers-data.tmp
	cat ${CURRENTDIR}/worldometers-data.tmp
        echo ""
        printf "FUENTE: https://www.worldometers.info/coronavirus/"
        echo ""
        echo ""
	urldata=$(python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1])" "$(cat ${CURRENTDIR}/worldometers-data.tmp)")
	rm ${CURRENTDIR}/worldometers-data.tmp
}
RAW=$(curl -s "https://www.worldometers.info/coronavirus/" | sed 's/<tr/\n<tr/g' | grep "${COUNTRY}" | grep '<tr style="">' | sed 's/<td/\n<td/g' | grep ^'<td' | sed 's/<!--//g' | sed 's/-->//g')

TC=$(echo "${RAW}" | head -2 | tail -1 | grep -Po '>\K.*?(?=<)' | sed 's/^ //g' | sed 's/ $//g' | sed 's/^$/-/g')
NC=$(echo "${RAW}" | head -4 | tail -1 | grep -Po '>\K.*?(?=<)' | sed 's/^ //g' | sed 's/ $//g' | sed 's/^$/-/g')
TD=$(echo "${RAW}" | head -5 | tail -1 | grep -Po '>\K.*?(?=<)' | sed 's/^ //g' | sed 's/ $//g' | sed 's/^$/-/g')
ND=$(echo "${RAW}" | head -6 | tail -1 | grep -Po '>\K.*?(?=<)' | sed 's/^ //g' | sed 's/ $//g' | sed 's/^$/-/g')
RC=$(echo "${RAW}" | head -7 | tail -1 | grep -Po '>\K.*?(?=<)' | sed 's/^ //g' | sed 's/ $//g' | sed 's/^$/-/g')
AC=$(echo "${RAW}" | head -9 | tail -1 | grep -Po '>\K.*?(?=<)' | sed 's/^ //g' | sed 's/ $//g' | sed 's/^$/-/g')
CC=$(echo "${RAW}" | head -10 | tail -1 | grep -Po '>\K.*?(?=<)' | sed 's/^ //g' | sed 's/ $//g' | sed 's/^$/-/g')
PM=$(echo "${RAW}" | head -12 | tail -1 | grep -Po '>\K.*?(?=<)' | sed 's/^ //g' | sed 's/ $//g' | sed 's/^$/-/g')

if [[ ! -z ${TC} ]]; then
	if [[ -f ${LASTUPDATEFILE} ]]; then
		CMP1=$(printf "${TC}|${NC}|${TD}|${ND}|${RC}|${AC}|${CC}|${PM}" | md5sum | awk '{print $1}')
		CMP2=$(md5sum ${LASTUPDATEFILE} | awk '{print $1}')
		if [[ ${CMP1} != ${CMP2} ]]; then
			sendData "${TC}" "${NC}" "${TD}" "${ND}" "${RC}" "${AC}" "${CC}" "${PM}"
			printf "${TC}|${NC}|${TD}|${ND}|${RC}|${AC}|${CC}|${PM}" > ${LASTUPDATEFILE}
		fi
	else
		sendData "${TC}" "${NC}" "${TD}" "${ND}" "${RC}" "${AC}" "${CC}" "${PM}"
		printf "${TC}|${NC}|${TD}|${ND}|${RC}|${AC}|${CC}|${PM}" > ${LASTUPDATEFILE}
        rm /home/blackout/.covid-19/.worldometers-corona.log
	fi
fi
