#!/bin/bash

COUNTRY="Mexico" # Example: Indonesia (Worldometers format)

CURRENTDIR="$(cd "$(dirname "$0")"; pwd)"
LASTUPDATEFILE="${CURRENTDIR}/.worldometers-corona.log"

function sendData() {
	echo ""
	echo "México:"
	printf "Casos totales  : $1\n" >> ${CURRENTDIR}/worldometers-data.tmp
	printf "Nuevos casos   : $2\n" >> ${CURRENTDIR}/worldometers-data.tmp
	printf "Muertes totales: $3\n" >> ${CURRENTDIR}/worldometers-data.tmp
	printf "Muertes nuevas : $4\n" >> ${CURRENTDIR}/worldometers-data.tmp
	printf "Recuperados    : $5\n" >> ${CURRENTDIR}/worldometers-data.tmp
	printf "Casos activos  : $6\n" >> ${CURRENTDIR}/worldometers-data.tmp
	printf "Casos criticos : $7\n" >> ${CURRENTDIR}/worldometers-data.tmp
	printf "CT / Promedio  : $8\n" >> ${CURRENTDIR}/worldometers-data.tmp
	echo ""
	cat ${CURRENTDIR}/worldometers-data.tmp
	echo ""
	echo "Fuente: https://www.worldometers.info/coronavirus/"
	echo ""
	urldata=$(python -c "import sys, urllib as ul; print ul.quote_plus(sys.argv[1])" "$(cat ${CURRENTDIR}/worldometers-data.tmp)")
	rm ${CURRENTDIR}/worldometers-data.tmp
}

HTMLDUMP="/tmp/wom-coronavirus.html"
echo '<table>' > ${HTMLDUMP}.tmp
curl -s "https://www.worldometers.info/coronavirus/" | sed ':a;N;$!ba;s/\n/ /g' | sed 's/<tr/\n<tr/g' | sed 's/<\/tr>/<\/tr>\n/g' | grep '<tr' | grep "<th \|${COUNTRY}" >> ${HTMLDUMP}.tmp
echo '</table>' >> ${HTMLDUMP}.tmp
if [[ -f ${HTMLDUMP} ]]; then
	rm ${HTMLDUMP}
fi
##### REFORMATING ######
cat ${HTMLDUMP}.tmp | sed 's/<td[^>]*>/<td>/g' | sed 's/<th[^>]*>/<th>/g' | sed 's/<tr[^>]*>/<tr>/g' | sed 's/<br \/>/ /g' | sed 's/> />/g' | sed 's/ </</g' >> ${HTMLDUMP}.tmpx
rm ${HTMLDUMP}.tmp
cat ${HTMLDUMP}.tmpx | sed 's/<!--/\n<!--/g' | sed 's/-->/-->\n/g' | grep -v '<!--' | sed ':a;N;$!ba;s/\n/ /g' | sed 's/<tr/\n<tr/g' | sed 's/ </</g' | sed 's/> />/g' >> ${HTMLDUMP}.tmp
rm ${HTMLDUMP}.tmpx
mv ${HTMLDUMP}.tmp ${HTMLDUMP}
########################

TC=$(cat ${HTMLDUMP} | grep -Po '<td>\K.*?(?=<\/td>)' | head -2 | tail -1)
NC=$(cat ${HTMLDUMP} | grep -Po '<td>\K.*?(?=<\/td>)' | head -3 | tail -1)
TD=$(cat ${HTMLDUMP} | grep -Po '<td>\K.*?(?=<\/td>)' | head -4 | tail -1)
ND=$(cat ${HTMLDUMP} | grep -Po '<td>\K.*?(?=<\/td>)' | head -5 | tail -1)
RC=$(cat ${HTMLDUMP} | grep -Po '<td>\K.*?(?=<\/td>)' | head -6 | tail -1)
AC=$(cat ${HTMLDUMP} | grep -Po '<td>\K.*?(?=<\/td>)' | head -7 | tail -1)
CC=$(cat ${HTMLDUMP} | grep -Po '<td>\K.*?(?=<\/td>)' | head -8 | tail -1)
PM=$(cat ${HTMLDUMP} | grep -Po '<td>\K.*?(?=<\/td>)' | head -9 | tail -1)

if [[ ! -z ${TC} ]]; then
	if [[ -f ${LASTUPDATEFILE} ]]; then
		CMP1=$(printf "${TC}|${NC}|${TD}|${ND}|${RC}|${AC}|${CC}|${PM}" | md5sum | awk '{print $1}')
		CMP2=$(md5sum ${LASTUPDATEFILE} | awk '{print $1}')
		if [[ ${CMP1} != ${CMP2} ]]; then
			sendData "${TC}" "${NC}" "${TD}" "${ND}" "${RC}" "${AC}" "${CC}" "${PM}"
			printf "${TC}|${NC}|${TD}|${ND}|${RC}|${AC}|${CC}|${PM}" > ${LASTUPDATEFILE}
		fi
	else
		sendData "${TC}" "${NC}" "${TD}" "${ND}" "${RC}" "${AC}" "${CC}" "${PM}"
		printf "${TC}|${NC}|${TD}|${ND}|${RC}|${AC}|${CC}|${PM}" > ${LASTUPDATEFILE}
		rm /home/blackout/.covid-19/.worldometers-corona.log
	fi
fi
